// Extract PCX Palette - Cyril BARBATO 2017
// * DISCLAIMER OF ALL WARRANTIES *
#include <stdio.h>
typedef struct _PixColorStr
{
   unsigned char r, g, b;
} PixColorStr;

int main(int argc , char **argv) {
	FILE *fptr;
	PixColorStr pixelcolor;
	int n;
	long int filesize;
   if (argc!=2) {
		printf("\nExtrPal for Extract PCX Palette (2017) Cyril BARBATO\n\n");
		printf("Usage :\n\n");
		printf("      extrpal [imagefile.pcx] > [palette.txt]\n\n");
		return 1;
	   
   }
   if ((fptr = fopen(argv[1],"rb")) == NULL){
       printf("Error! opening file");
		return(1);
   }
   
   // printf("size of PixColorStr = %d\n", sizeof(PixColorStr));
   // Moves the cursor to the end of the file
	fseek(fptr, sizeof(PixColorStr), SEEK_END);
	filesize = ftell(fptr);
	fseek(fptr, filesize - 257 * sizeof(PixColorStr), SEEK_SET);
	
	for(n = 0; n <= 255; ++n) {
      fread(&pixelcolor, sizeof(PixColorStr), 1, fptr); 
      printf("%d %d %d\n", pixelcolor.r, pixelcolor.g, pixelcolor.b);
   }
   printf(";Generated by ExtrPal for Extract PCX Palette (2017) Cyril BARBATO");
   fclose(fptr); 
  
   return 0;
}